Repository pure-admin/vue-pure-admin, pull requests merged in 2023-10, with the labels that each got.

#747 feat: 支持多标签页打开已经登录的系统后无需再登录并添加`7`天内免登录功能
  locales/en.yaml
  locales/zh-CN.yaml
  package.json
  pnpm-lock.yaml
  src/layout/components/setting/index.vue
  src/router/index.ts
  src/router/utils.ts
  src/store/modules/types.ts
  src/store/modules/user.ts
  src/utils/auth.ts
  src/views/login/index.vue
  src/views/permission/page/index.vue
Labels: test:pass

#758 feat: 添加页脚
  public/platform-config.json
  src/layout/components/appMain.vue
  src/layout/components/footer/index.vue
  src/layout/components/setting/index.vue
  src/layout/hooks/useLayout.ts
  src/utils/responsive.ts
  types/global.d.ts
Labels: feature request, test:pass

#764 feat: 添加`AnimateCss`选择器组件`ReAnimateSelector`
  locales/en.yaml
  locales/zh-CN.yaml
  src/components/ReAnimateSelector/index.ts
  src/components/ReAnimateSelector/src/animate.ts
  src/components/ReAnimateSelector/src/index.vue
  src/router/modules/components.ts
  src/views/components/animatecss/index.vue
Labels: PR::WIP, v5.0.0

#780 perf: 优化`PureTableBar`组件的列设置弹出框，设置最大高度，超出可滚动
  src/components/RePureTableBar/src/bar.tsx
Labels: test:pass
