Repository pure-admin/vue-pure-admin, pull requests merged in 2024-01, with the labels that each got.

#842 refactor: 优化主题色
  public/platform-config.json
  src/layout/components/panel/index.vue
  src/layout/components/setting/index.vue
  src/layout/components/sidebar/leftCollapse.vue
  src/layout/hooks/useDataThemeChange.ts
  src/layout/hooks/useLayout.ts
  src/layout/index.vue
  src/layout/theme/index.ts
  src/store/modules/epTheme.ts
  src/style/sidebar.scss
  src/utils/responsive.ts
  types/global.d.ts
  types/router.d.ts
Labels: PR::WIP, v5.0.0

#848 refactor: 带来更美观精致的首页
  build/optimize.ts
  mock/list.ts
  package.json
  pnpm-lock.yaml
  src/api/list.ts
  src/plugins/echarts/index.ts
  src/plugins/echarts/theme.json
  src/style/dark.scss
  src/views/pure-table/high/echarts/columns.tsx
  src/views/welcome/components/Bar.vue
  src/views/welcome/components/Github.vue
  src/views/welcome/components/Line.vue
  src/views/welcome/components/Pie.vue
  src/views/welcome/components/chart/bar.vue
  src/views/welcome/components/chart/index.ts
  src/views/welcome/components/chart/line.vue
  src/views/welcome/components/chart/round.vue
  src/views/welcome/components/columns.tsx
  src/views/welcome/components/table/columns.tsx
  src/views/welcome/components/table/empty.svg
  src/views/welcome/components/table/index.vue
  src/views/welcome/data.ts
  src/views/welcome/index.vue
  src/views/welcome/utils.ts
Labels: v5.0.0

#869 feat: 添加整体风格自适应操作系统浅色、深色、自动主题功能，让平台充满现代气息
  README.md
  public/logo.svg
  public/platform-config.json
  src/assets/login/avatar.svg
  src/assets/svg/system.svg
  src/components/ReFlowChart/src/assets/iconfont/iconfont.svg
  src/components/ReSegmented/src/index.tsx
  src/components/ReSegmented/src/type.ts
  src/layout/components/setting/index.vue
  src/layout/hooks/useDataThemeChange.ts
  src/layout/hooks/useLayout.ts
  src/layout/index.vue
  src/style/dark.scss
  src/style/element-plus.scss
  src/utils/responsive.ts
  src/views/components/message/index.vue
  src/views/login/index.vue
  types/global.d.ts
Labels: PR::WIP, v5.0.0

#873 Keep alive frame
  mock/asyncRoutes.ts
  src/layout/components/appMain.vue
  src/layout/components/keepAliveFrame/index.vue
  src/layout/components/keepAliveFrame/useMultiFrame.ts
  src/layout/frameView.vue
Labels: test:waiting, nice pr

#884 perf: 标签页可按滑动力度进行左右滑动
  package.json
  pnpm-lock.yaml
  src/layout/components/tag/index.scss
  src/layout/components/tag/index.vue
  src/layout/hooks/useTag.ts
  src/views/login/index.vue
Labels: v5.0.0

#894 feat(function): 为图片裁剪组件添加裁剪区域能够关闭右键菜单的功能
  src/components/ReCropper/src/index.tsx
Labels: nice pr
