Repository pure-admin/vue-pure-admin, pull requests merged in 2024-03, with the labels that each got.

#936 feat: 菜单支持`a`标签右键的所有浏览器行为（在新标签页中、新窗口中打开链接，拖拽到新标签页打开等）
  src/layout/components/sidebar/linkItem.vue
  src/layout/components/sidebar/logo.vue
  src/layout/components/sidebar/sidebarItem.vue
  src/layout/types.ts
  src/style/sidebar.scss
Labels: test:pass, nice pr, v5.1.0

#950 style: 重构标签页`UI`，点击关闭按钮更方便
  src/layout/components/tag/index.scss
  src/layout/components/tag/index.vue
  src/layout/hooks/useTag.ts
  src/style/dark.scss
Labels: test:pass, v5.1.0

#901 feat: 菜单搜索新增搜索历史和收藏功能
  public/platform-config.json
  src/layout/components/search/components/SearchFooter.vue
  src/layout/components/search/components/SearchHistory.vue
  src/layout/components/search/components/SearchHistoryItem.vue
  src/layout/components/search/components/SearchModal.vue
  src/layout/components/search/components/SearchResult.vue
  src/layout/components/search/types.ts
  src/utils/localforage/index.ts
  types/global.d.ts
Labels: test:pass, nice pr, v5.1.0

#951 feat: 添加系统监控-在线用户、登录日志页面示例
  locales/en.yaml
  locales/zh-CN.yaml
  mock/asyncRoutes.ts
  mock/system.ts
  package.json
  pnpm-lock.yaml
  src/api/system.ts
  src/components/ReIcon/src/offlineIcon.ts
  src/router/enums.ts
  src/views/monitor/logs/login/hook.tsx
  src/views/monitor/logs/login/index.vue
  src/views/monitor/logs/operation.vue
  src/views/monitor/logs/system.vue
  src/views/monitor/online/hook.tsx
  src/views/monitor/online/index.vue
  src/views/monitor/utils.ts
  src/views/system/user/utils/hook.tsx
Labels: test:pass, v5.2.0

#958 feat: 添加基于`ElTour`实现的漫游式引导
  src/style/element-plus.scss
  src/views/guide/index.vue
Labels: nice pr

#956 feat: 新增v-ripple指令(水波纹效果)
  locales/en.yaml
  locales/zh-CN.yaml
  src/directives/index.ts
  src/directives/ripple/index.scss
  src/directives/ripple/index.ts
  src/router/modules/able.ts
  src/views/able/ripple.vue
  types/global.d.ts
Labels: nice pr, CodeReview::Waiting

#969 chore: 将全屏按钮置于顶部，使其显眼且易于操作
  src/layout/components/navbar.vue
  src/layout/components/sidebar/fullScreen.vue
  src/layout/components/sidebar/horizontal.vue
  src/layout/components/sidebar/mixNav.vue
  src/layout/components/tag/index.vue
  src/layout/hooks/useNav.ts
  src/layout/hooks/useTag.ts
  src/style/sidebar.scss
  src/views/guide/index.vue
  types/global.d.ts
Labels: test:pass, v5.2.0

#968 feat: 内容区添加全局`Stretch`配置，可自定义紧凑页面，轻松找到所需信息
  public/platform-config.json
  src/layout/components/appMain.vue
  src/layout/components/setting/index.vue
  src/layout/hooks/useLayout.ts
  src/utils/responsive.ts
  types/global.d.ts
Labels: test:pass, nice pr

#984 feat: 完善角色管理-菜单权限功能，新颖的交互体验
  mock/system.ts
  src/api/system.ts
  src/views/system/role/index.vue
  src/views/system/role/utils/hook.tsx
Labels: test:pass, v5.2.0

#997 feat(components): 为`segmented`组件新增`block`属性，可使其适合父元素宽度
  src/components/ReSegmented/src/index.css
  src/components/ReSegmented/src/index.tsx
  src/views/components/segmented.vue
Labels: test:pass, nice pr

#1001 feat: 添加`vue-flow`流程图示例
  package.json
  pnpm-lock.yaml
  src/router/enums.ts
  src/router/modules/vueflow.ts
  src/views/vue-flow/layouting/animationEdge.vue
  src/views/vue-flow/layouting/icon.vue
  src/views/vue-flow/layouting/index.vue
  src/views/vue-flow/layouting/initialElements.ts
  src/views/vue-flow/layouting/processNode.vue
  src/views/vue-flow/layouting/useLayout.ts
  src/views/vue-flow/layouting/useRunProcess.ts
  src/views/vue-flow/layouting/useShuffle.ts
Labels: test:pass, v5.2.0

#999 feat: 添加表单示例，可通过`JSON`格式配置生成
  locales/en.yaml
  locales/zh-CN.yaml
  package.json
  pnpm-lock.yaml
  src/App.vue
  src/components/ReIcon/src/offlineIcon.ts
  src/router/enums.ts
  src/router/modules/form.ts
  src/views/components/check-card.vue
  src/views/schema-form/form/base.vue
  src/views/schema-form/form/dialog.vue
  src/views/schema-form/form/drawer.vue
  src/views/schema-form/form/search.vue
  src/views/schema-form/form/steps.vue
  src/views/schema-form/index.vue
  src/views/schema-form/list.tsx
  types/shims-vue.d.ts
Labels: test:pass, v5.2.0

#1016 feat: `ReSegmented`分段控制器新增`size`属性，以便适配不同的场景
  src/components/ReSegmented/src/index.css
  src/components/ReSegmented/src/index.tsx
  src/views/components/segmented.vue
Labels: test:pass, nice pr

#1021 feat: 添加`MQTT`示例
  .vscode/settings.json
  locales/en.yaml
  locales/zh-CN.yaml
  package.json
  pnpm-lock.yaml
  src/router/modules/able.ts
  src/views/able/mqtt-client.vue
Labels: test:pass, nice pr
